spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ddaggeundb@gmail.com
    password: ddaggeun1906
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable=true


