# PostgreSQL DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/appdb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=app
spring.datasource.password=secret

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Seoul


ethereum.network.url=http://127.0.0.1:7545
ethereum.private.key=0x69058419df307522c5f5da6c3b8dc041957c1cd8e94358dbb75ae850c5258ab8
ethereum.contract.address=0x97CF04FE4069F1E3aF013Ad878EB7C240a12687b

# File Upload Settings (??)
app.upload.path=C:/DDADDABLCH
app.upload.max-file-size=5242880